# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7166bf74b612f4943af7badac768ae4f11d4726527e4a56e58eb25e57c8186ab6ca16660c2c3790a2b638ae00a95327f48ca879f74678e21edddc3999dc2b55

test:
  secret_key_base: e33797089edef156f3e17b4e83d060ad2244f2fb168f7c388402c60d1aaaef5cfe798cfc55a900d4776cfe1dcc4a8b06105852281110a8633bb841e02a5d5c20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
